version: "3.7"

services:
  app:
    build:
      context: code
      target: app_dev
    volumes:
      - ./code:/app
    extra_hosts:
      - host.docker.internal:host-gateway

  caddy:
    image: caddy:2.7
    environment:
      SERVER_NAME: ${CADDY_SERVER_NAME}
      APP_URL: ${CADDY_APP_URL}
    ports:
      - ${CADDY_EXPOSE_HTTP:-80}:80
    volumes:
      - ./code/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./code:/app

  redis:
      image: redis:7.2.4
      environment:
          REDIS_PASSWORD: password
      command:
          - /bin/sh
          - -c
          - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
      ports:
          - ${REDIS_EXPOSE_PORT:-6379}:6379
      volumes:
          - ./.docker-vols/redis:/data
