apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Values.appIngressName }}
    annotations:
        cert-manager.io/cluster-issuer: {{ .Values.certIssuerName | quote }}
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    ingressClassName: {{ .Values.appIngress.className }}
    rules:
        - host: {{ .Values.appIngress.host }}
          http:
              paths:
                  - backend:
                        service:
                            name: {{ .Values.appServiceName }}
                            port:
                                number: {{ .Values.appServiceExposePort }}
                    pathType: Prefix
                    path: /
    tls:
        - hosts:
            - {{ .Values.appIngress.host }}
          secretName: {{ .Values.certIssuerSecretName | quote }}

