name: Build image

on:
    workflow_call:
        inputs:
            target:
                required: false
                type: string
                default: ${{ (github.ref_type == 'tag' || github.ref_name == 'master') && 'app_prod' || 'app_dev'}}
            tag:
                required: false
                type: string
                default: jackobsmonarch/tg-app:${{ (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.head_ref || github.ref_name }}
            dockerfile:
                required: false
                type: string
                default: ./code/Dockerfile
            push_to_hub:
                required: false
                type: boolean
                default: true

jobs:
    build-and-push:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Login to Docker Hub
              if: ${{ inputs.push_to_hub }}
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.dockerhub_username }}
                  password: ${{ secrets.dockerhub_token }}
            - name: Build the Docker image
              run: docker build --file=${{ inputs.dockerfile }} --target=${{ inputs.target }} --tag=${{ inputs.tag }} ./code
            - name: Push to DockerHub
              if: ${{ inputs.push_to_hub }}
              run: docker push ${{ inputs.tag }}
