name: Build, Push and Lint

on:
    push:
        branches:
            - master
        tags:
            - 20[2-9][0-9]-[0-1][1-9]-[0-3][0-9].*
    pull_request:
        branches:
            - '**'

jobs:
    build:
        uses: ./.github/workflows/build-image-reusable.yml
        secrets: inherit
    lint:
        uses: ./.github/workflows/lints-reusable.yml
        secrets: inherit
        needs:
            - build
    test:
        uses: ./.github/workflows/tests-reusable.yml
        secrets: inherit
        needs:
            - build
