name: Tests

on:
    workflow_call:
        inputs:
            tag:
                required: false
                type: string
                default: jackobsmonarch/tg-app:${{ (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.head_ref || github.ref_name }}

jobs:
    test:
        runs-on: ubuntu-22.04
        container:
            image: ${{ inputs.tag }}
        defaults:
            run:
                working-directory: /app
        steps:
            -   name: Auto-tests
                run: php bin/phpunit
